name: Aravis-macOS

on: push
 

jobs:
  macos:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-python@v4
      with:
        python-version: '3.x'
    - name: Unbreak Python in Github Actions
      run: |
        find /usr/local/bin -lname '*/Library/Frameworks/Python.framework/*' -delete
        sudo rm -rf /Library/Frameworks/Python.framework/
        brew install --force python3 && brew unlink python3 && brew unlink python3 && brew link --overwrite python3
    - name: Install dependencies
      run: |
        brew update
        brew install meson ninja gcc gettext intltool libxml2 libusb gstreamer gnome-icon-theme gobject-introspection glib
    - name: Build
      run: |
        mkdir build
        meson setup -Ddocumentation=disabled -Dusb=enabled -Dviewer=enabled -Dgv-n-buffers=1 -Dprefix=${{ github.workspace }}/install -Dintrospection=enabled build . 
        meson compile -C ./build
        meson install -C ./build
      env:
        CC: gcc
    - name: Tests
      run: meson test -C build/ -v
    - uses: actions/upload-artifact@v3
      with:
        name: aravis-${{env.ARAVIS_VER}}-macos.tar.gz
        path: ${{ github.workspace }}/install/*

